[project]
name = "benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "qiskit>=2.1.1",
    "qiskit-aer>=0.17.1",
    "qiskit-ibm-runtime>=0.40.1",
    "qulacs>=0.6.12",
]
